export const USER = {
  LOGIN: 'LOGIN'

}

export const CLAZZ = {
  SET_ALL_CLAZZ: 'SET_ALL_CLAZZ',
  SHOW_CREATE_DIALOG: 'SHOW_CREATE_DIALOG',
  HIDE_CREATE_DIALOG: 'HIDE_CREATE_DIALOG',
  CREATE: 'CREATE'

}
